In [3]:
import numpy as np
data = np.random.randint(1,100, (6,5))

In [6]:
data

array([[26, 55, 87, 54, 27],
       [ 9, 95, 94, 28, 13],
       [14, 12, 68,  4, 27],
       [57,  5, 13, 85, 34],
       [38, 46, 59, 83, 32],
       [64, 99, 10, 75, 28]])

Retrieve first two elements of 2nd, 3rd, and 6th rows

In [5]:
data[[1, 2, 5]][:, [0, 1]]

array([[ 9, 95],
       [14, 12],
       [64, 99]])

Extract 2nd and 3rd row of the new data

(using the original data)

In [7]:
data[[1, 2, 5]][1:, [0, 1]]

array([[14, 12],
       [64, 99]])

In [29]:
my_data = np.random.randn(4, 4)
tr_data = my_data.T
dot_prod = my_data.dot(tr_data)

In [30]:
print("Original Array:\n", my_data)
print("\nTransposed Array:\n", tr_data)
print("\nDot Product:\n", dot_prod)

Original Array:
 [[ 0.58469609 -0.6143388  -0.3624524   1.90185614]
 [ 0.47611761 -0.53560539 -0.83578166  0.61279244]
 [ 0.00242727 -0.07293691 -0.80008479  0.31886737]
 [ 2.24095303 -0.80186122 -0.16542995 -0.20512318]]

Transposed Array:
 [[ 0.58469609  0.47611761  0.00242727  2.24095303]
 [-0.6143388  -0.53560539 -0.07293691 -0.80186122]
 [-0.3624524  -0.83578166 -0.80008479 -0.16542995]
 [ 1.90185614  0.61279244  0.31886737 -0.20512318]]

Dot Product:
 [[4.46771019 2.07580142 0.94265971 1.47273664]
 [2.07580142 1.58760668 0.90431678 1.50900377]
 [0.94265971 0.90431678 0.74713775 0.13087558]
 [1.47273664 1.50900377 0.13087558 5.73429448]]


In [ ]:
my_data = np.ones()

In [33]:
print(my_data)
print(tr_data)

[[ 0.58469609 -0.6143388  -0.3624524   1.90185614]
 [ 0.47611761 -0.53560539 -0.83578166  0.61279244]
 [ 0.00242727 -0.07293691 -0.80008479  0.31886737]
 [ 2.24095303 -0.80186122 -0.16542995 -0.20512318]]
[[ 0.58469609  0.47611761  0.00242727  2.24095303]
 [-0.6143388  -0.53560539 -0.07293691 -0.80186122]
 [-0.3624524  -0.83578166 -0.80008479 -0.16542995]
 [ 1.90185614  0.61279244  0.31886737 -0.20512318]]


In [31]:
my_data[0:2, 0:2]*tr_data[0:2, 0:2]

array([[ 0.34186952, -0.29249752],
       [-0.29249752,  0.28687314]])

In [34]:
my_data.swapaxes(0,1)

array([[ 0.58469609,  0.47611761,  0.00242727,  2.24095303],
       [-0.6143388 , -0.53560539, -0.07293691, -0.80186122],
       [-0.3624524 , -0.83578166, -0.80008479, -0.16542995],
       [ 1.90185614,  0.61279244,  0.31886737, -0.20512318]])

In [37]:
my_data.reshape(4,4)

array([[ 0.58469609, -0.6143388 , -0.3624524 ,  1.90185614],
       [ 0.47611761, -0.53560539, -0.83578166,  0.61279244],
       [ 0.00242727, -0.07293691, -0.80008479,  0.31886737],
       [ 2.24095303, -0.80186122, -0.16542995, -0.20512318]])

In [39]:
arr = np.random.randint(1, 10, (1, 24))

arr_3d = arr.reshape(2, 4, 3)

In [40]:
print(arr)

print(arr_3d)

[[9 7 2 6 4 7 5 3 5 1 6 6 8 1 4 5 2 7 2 2 7 3 1 4]]
[[[9 7 2]
  [6 4 7]
  [5 3 5]
  [1 6 6]]

 [[8 1 4]
  [5 2 7]
  [2 2 7]
  [3 1 4]]]


In [44]:
print(arr_3d[0])

print(arr_3d[:1])

[[9 7 2]
 [6 4 7]
 [5 3 5]
 [1 6 6]]
[[[9 7 2]
  [6 4 7]
  [5 3 5]
  [1 6 6]]]


In [45]:
data = np.random.randint(1, 50, (4, 5))
data

array([[28, 34, 17, 34, 28],
       [23,  1,  5, 32, 16],
       [29, 14, 10,  7, 12],
       [39, 35,  2, 23, 22]])

In [46]:
data[data%2==0] = 0

In [47]:
data

array([[ 0,  0, 17,  0,  0],
       [23,  1,  5,  0,  0],
       [29,  0,  0,  7,  0],
       [39, 35,  0, 23,  0]])

In [48]:
my_sum = np.sum(data[data%2!=0])

my_sum

179

In [1]:
import pandas as pd

In [2]:
x = pd.Series([4,7,-5,3])
print(x)

0    4
1    7
2   -5
3    3
dtype: int64


In [3]:
print(x.values)
print(x.index)

[ 4  7 -5  3]
RangeIndex(start=0, stop=4, step=1)


In [4]:
a = pd.Series([41, 71, -5, 3, 38], index=['d', 'a', 'b', 'c', 'c'])
print(a, "\n", a.values, "\n", a.index)

d    41
a    71
b    -5
c     3
c    38
dtype: int64 
 [41 71 -5  3 38] 
 Index(['d', 'a', 'b', 'c', 'c'], dtype='object')


In [5]:
a.name

fancy index

In [6]:
print(a[['c', 'd']])

c     3
c    38
d    41
dtype: int64


In [7]:
print(a['a'])

71


"in" will work with indices in dataseries

In [8]:
x = 'f' in a

In [9]:
x

False

In [11]:
city = {'Noida': 5000, 'Delhi': 3500}

cityseries = pd.Series(city)
print(cityseries)

Noida    5000
Delhi    3500
dtype: int64


In [12]:
dictionary = {'A':[50,60], 'B':10, 'C':80}
series = pd.Series(dictionary)
series

A    [50, 60]
B          10
C          80
dtype: object

In [13]:
dictionary = {'A':50, 'B':10, 'C':80}
series = pd.Series(dictionary)
print(series)
series = pd.Series(dictionary, index=['B', 'C', 'A'])
print(series)

A    50
B    10
C    80
dtype: int64
B    10
C    80
A    50
dtype: int64


In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [4]:
data = [1,2,3,4,5]

df = pd.DataFrame(data)
print(df)

   0
0  1
1  2
2  3
3  4
4  5


In [7]:
print(df.index)
print(df.columns)

RangeIndex(start=0, stop=5, step=1)
RangeIndex(start=0, stop=1, step=1)


In [8]:
df[0]

0    1
1    2
2    3
3    4
4    5
Name: 0, dtype: int64

In [9]:
df[0:2]

0
0  1
1  2

In [10]:
df.iloc[0:2,0]

0    1
1    2
Name: 0, dtype: int64

In [11]:
df.loc[0:2,0]

0    1
1    2
2    3
Name: 0, dtype: int64

In [12]:
data = [['Alia', 10], ['Bob', 12], ['Clarke', 13], ['xxx', 20]]

df = pd.DataFrame(data, columns = ['Name', 'Age'])
print(df)

     Name  Age
0    Alia   10
1     Bob   12
2  Clarke   13
3     xxx   20


In [13]:
df['Name']

0      Alia
1       Bob
2    Clarke
3       xxx
Name: Name, dtype: object

In [15]:
df.loc[:, 'Name']

0      Alia
1       Bob
2    Clarke
3       xxx
Name: Name, dtype: object

In [16]:
df.iloc[:, 0]

0      Alia
1       Bob
2    Clarke
3       xxx
Name: Name, dtype: object

In [18]:
df[['Name', 'Age']]

Name  Age
0    Alia   10
1     Bob   12
2  Clarke   13
3     xxx   20

In [22]:
data = {'Name':['Tom','Jack','Steve','Ricky'], 'Age':[28,34,29,32]}
df = pd.DataFrame(data, index=['I', 'II', 'III', 'IV'])
print(df)
print(df.shape)

      Name  Age
I      Tom   28
II    Jack   34
III  Steve   29
IV   Ricky   32
(4, 2)


In [23]:
print(df.size)

8


In [24]:
print(len(df))

4


In [45]:
print(df.loc['I',:])

Name    Tom
Age      28
Name: I, dtype: object


In [46]:
print(df.loc[['I', 'III'], 'Name'])

SNo
I        Tom
III    Steve
Name: Name, dtype: object


In [42]:
print(df.loc[['II', 'IV'],:])


     Name  Age
II   Jack   34
IV  Ricky   32


In [43]:
df.index.name = 'SNo'

In [44]:
print(df)

      Name  Age
SNo            
I      Tom   28
II    Jack   34
III  Steve   29
IV   Ricky   32


In [49]:
df.loc['II']

Name    Jack
Age       34
Name: II, dtype: object

In [54]:
display(df.iloc[2])

Name    Steve
Age        29
Name: III, dtype: object

In [48]:
display(df)

Name  Age
SNo            
I      Tom   28
II    Jack   34
III  Steve   29
IV   Ricky   32

In [25]:
d = {'one': pd.Series([1,2,3], index=['a','e','c']), 'two': pd.Series([1,2,3,4], index=['a','b','c','d'])}


In [4]:
df = pd.DataFrame(d)
print(df)

   one  two
a  1.0  1.0
b  NaN  2.0
c  3.0  3.0
d  NaN  4.0
e  2.0  NaN


In [66]:
# from cmath import isnan


# np.argwhere(isnan(df.columns))

TypeError: must be real number, not Index

In [7]:
pd.notnull(df)

one    two
a   True   True
b  False   True
c   True   True
d  False   True
e   True  False

In [8]:
df.values

array([[ 1.,  1.],
       [nan,  2.],
       [ 3.,  3.],
       [nan,  4.],
       [ 2., nan]])

In [26]:
df['three'] = pd.Series([10,20,30], index=['a','b','c'])
display(df)

df['four'] = df['two']+df['three']
display(df)

one  New  two  three  four  seven    six
a  1.0   34  1.0   10.0  11.0      7  False
b  NaN   45  2.0   20.0  22.0      7  False
c  3.0   32  3.0   30.0  33.0      7   True
d  NaN   56  4.0    NaN   NaN      7  False
e  2.0   21  NaN    NaN   NaN      7   True

one  New  two  three  four  seven    six
a  1.0   34  1.0   10.0  11.0      7  False
b  NaN   45  2.0   20.0  22.0      7  False
c  3.0   32  3.0   30.0  33.0      7   True
d  NaN   56  4.0    NaN   NaN      7  False
e  2.0   21  NaN    NaN   NaN      7   True

In [27]:
df['five'] = pd.Series([10,20,30], index=['e','f','c'])
print(df)

   one  New  two  three  four  seven    six  five
a  1.0   34  1.0   10.0  11.0      7  False   NaN
b  NaN   45  2.0   20.0  22.0      7  False   NaN
c  3.0   32  3.0   30.0  33.0      7   True  30.0
d  NaN   56  4.0    NaN   NaN      7  False   NaN
e  2.0   21  NaN    NaN   NaN      7   True  10.0


In [29]:
df['seven'] = 7

In [30]:
df['six'] = df.one>1

In [19]:
display(df)

one  two  three  four  five  seven    six
a  1.0  1.0   10.0  11.0   NaN      7  False
b  NaN  2.0   20.0  22.0   NaN      7  False
c  3.0  3.0   30.0  33.0  30.0      7   True
d  NaN  4.0    NaN   NaN   NaN      7  False
e  2.0  NaN    NaN   NaN  10.0      7   True

In [31]:
df.insert(1, 'New', [34, 45, 32, 56, 21])

ValueError: cannot insert New, already exists

In [21]:
display(df)

one  New  two  three  four  five  seven    six
a  1.0   34  1.0   10.0  11.0   NaN      7  False
b  NaN   45  2.0   20.0  22.0   NaN      7  False
c  3.0   32  3.0   30.0  33.0  30.0      7   True
d  NaN   56  4.0    NaN   NaN   NaN      7  False
e  2.0   21  NaN    NaN   NaN  10.0      7   True

In [32]:
del df['five']
print(df)

   one  New  two  three  four  seven    six
a  1.0   34  1.0   10.0  11.0      7  False
b  NaN   45  2.0   20.0  22.0      7  False
c  3.0   32  3.0   30.0  33.0      7   True
d  NaN   56  4.0    NaN   NaN      7  False
e  2.0   21  NaN    NaN   NaN      7   True


In [35]:
d1 = df.drop('one', axis=1)
display(df)
display(d1)

one  New  two  three  four  seven    six
a  1.0   34  1.0   10.0  11.0      7  False
b  NaN   45  2.0   20.0  22.0      7  False
c  3.0   32  3.0   30.0  33.0      7   True
d  NaN   56  4.0    NaN   NaN      7  False
e  2.0   21  NaN    NaN   NaN      7   True

New  two  three  four  seven    six
a   34  1.0   10.0  11.0      7  False
b   45  2.0   20.0  22.0      7  False
c   32  3.0   30.0  33.0      7   True
d   56  4.0    NaN   NaN      7  False
e   21  NaN    NaN   NaN      7   True

In [36]:
df.pop('two')

a    1.0
b    2.0
c    3.0
d    4.0
e    NaN
Name: two, dtype: float64

In [37]:
df.loc[{'a','e'},['seven', 'six']]

/tmp/ipykernel_70983/3111133419.py:1: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  df.loc[{'a','e'},['seven', 'six']]


seven    six
a      7  False
e      7   True

In [38]:
df.iloc[2:,2:]

three  four  seven    six
c   30.0  33.0      7   True
d    NaN   NaN      7  False
e    NaN   NaN      7   True

In [40]:
df.loc[['d','e'],['one','three']]

one  three
d  NaN    NaN
e  2.0    NaN

In [41]:
df.T

a      b     c      d     e
one      1.0    NaN   3.0    NaN   2.0
New       34     45    32     56    21
three   10.0   20.0  30.0    NaN   NaN
four    11.0   22.0  33.0    NaN   NaN
seven      7      7     7      7     7
six    False  False  True  False  True

In [42]:
df

one  New  three  four  seven    six
a  1.0   34   10.0  11.0      7  False
b  NaN   45   20.0  22.0      7  False
c  3.0   32   30.0  33.0      7   True
d  NaN   56    NaN   NaN      7  False
e  2.0   21    NaN   NaN      7   True

In [45]:
pop = {'Nev': {2001: 2.4, 2007: 2.9}, 'Ohio': {2002: 1.5, 2007: 1.7, 2000: 3.6}}
df = pd.DataFrame(pop)
display(df)

Nev  Ohio
2001  2.4   NaN
2007  2.9   1.7
2002  NaN   1.5
2000  NaN   3.6

In [56]:
df.columns.name = "State"

In [50]:
df.index.name = 'Year'

In [57]:
df

State  Nev  Ohio description
Year                        
2001   2.4   NaN        good
2007   2.9   1.7        good
2002   NaN   1.5        good
2000   NaN   3.6        good

In [52]:
df['description'] = 'good'

In [58]:
df

State  Nev  Ohio description
Year                        
2001   2.4   NaN        good
2007   2.9   1.7        good
2002   NaN   1.5        good
2000   NaN   3.6        good

In [59]:
df[df.columns[2]]

Year
2001    good
2007    good
2002    good
2000    good
Name: description, dtype: object

In [60]:
df.columns

Index(['Nev', 'Ohio', 'description'], dtype='object', name='State')

In [61]:
df.columns = ['X', 'Y', 'Z']

In [62]:
display(df)

X    Y     Z
Year                
2001  2.4  NaN  good
2007  2.9  1.7  good
2002  NaN  1.5  good
2000  NaN  3.6  good

In [63]:
df.columns[1] = 'zz'

TypeError: Index does not support mutable operations

In [64]:
df.index = [1900, 2000, 2003, 2020]

In [65]:
display(df)

X    Y     Z
1900  2.4  NaN  good
2000  2.9  1.7  good
2003  NaN  1.5  good
2020  NaN  3.6  good

In [ ]:
# 1st col val 2, 2nd cl rand val 0-5 3rd col max

In [75]:
d = {'one': pd.Series([2, 2, 2, 2, 2]), 'two': np.random.randint(0, 5, (5))}

In [76]:
df = pd.DataFrame(d)

In [77]:
df

one  two
0    2    2
1    2    0
2    2    2
3    2    3
4    2    3

In [86]:
df['three'] = df.max(axis=1)

In [87]:
df

one  two  three
0    2    2    2.0
1    2    0    2.0
2    2    2    2.0
3    2    3    3.0
4    2    3    3.0

In [26]:
import pandas as pd
import numpy as np

In [70]:


# marks = {"Amartya": {"DAV": 90, "IT": 95, "MP": 80, "ToC": 85}, "Shahnwaz": {"DAV": 80, "IT": 100, "MP": 85, "ToC": 99}, "Nilesh": {"DAV": 85, "IT": 96, "MP": 70, "ToC": 90}}
marks = {'Name': ['Amartya', 'Shahnwaz', 'Nilesh', 'Aditya'], 'DAV':[90, 80, 85, 70], 'IT':[95,100,96, 85], 'MP':[80,85,70, 65], 'ToC':[85,99,90, 90]}
df = pd.DataFrame(marks)
df

Name  DAV   IT  MP  ToC
0   Amartya   90   95  80   85
1  Shahnwaz   80  100  85   99
2    Nilesh   85   96  70   90
3    Aditya   70   85  65   90

In [71]:
df['Average'] = df[['DAV','IT','MP','ToC']].mean(axis=1)
df

Name  DAV   IT  MP  ToC  Average
0   Amartya   90   95  80   85    87.50
1  Shahnwaz   80  100  85   99    91.00
2    Nilesh   85   96  70   90    85.25
3    Aditya   70   85  65   90    77.50

In [73]:
df.loc['Sub Avg'] = df[['DAV','IT','MP','ToC']].mean().round(decimals=1)
df

Name   DAV     IT    MP   ToC  Average
0         Amartya  90.0   95.0  80.0  85.0    87.50
1        Shahnwaz  80.0  100.0  85.0  99.0    91.00
2          Nilesh  85.0   96.0  70.0  90.0    85.25
3          Aditya  70.0   85.0  65.0  90.0    77.50
Sub Avg       NaN  81.2   94.0  75.0  91.0      NaN

In [74]:
display(df[['DAV','IT','MP','ToC']][0:-1].describe())           #didn't include sub avg for descriptive statistics

DAV          IT         MP        ToC
count   4.000000    4.000000   4.000000   4.000000
mean   81.250000   94.000000  75.000000  91.000000
std     8.539126    6.377042   9.128709   5.830952
min    70.000000   85.000000  65.000000  85.000000
25%    77.500000   92.500000  68.750000  88.750000
50%    82.500000   95.500000  75.000000  90.000000
75%    86.250000   97.000000  81.250000  92.250000
max    90.000000  100.000000  85.000000  99.000000

In [75]:
df

Name   DAV     IT    MP   ToC  Average
0         Amartya  90.0   95.0  80.0  85.0    87.50
1        Shahnwaz  80.0  100.0  85.0  99.0    91.00
2          Nilesh  85.0   96.0  70.0  90.0    85.25
3          Aditya  70.0   85.0  65.0  90.0    77.50
Sub Avg       NaN  81.2   94.0  75.0  91.0      NaN

In [76]:
df['Grades'] = df.apply(lambda x: 'A' if x['Average']>90 else ('B' if x['Average']>80 else ('C' if x['Average']>70 else ('F' if x['Average']<33 else ('D')))), axis=1).head(-1)


In [77]:
df

Name   DAV     IT    MP   ToC  Average Grades
0         Amartya  90.0   95.0  80.0  85.0    87.50      B
1        Shahnwaz  80.0  100.0  85.0  99.0    91.00      A
2          Nilesh  85.0   96.0  70.0  90.0    85.25      B
3          Aditya  70.0   85.0  65.0  90.0    77.50      C
Sub Avg       NaN  81.2   94.0  75.0  91.0      NaN    NaN

In [83]:
df['Grades'].value_counts()

B    2
A    1
C    1
Name: Grades, dtype: int64